version: '3.5'
services:

  app:
    container_name: app
    build: 
      dockerfile: dockerfile
      context: .
    env_file:
      - .env.prod
    network_mode: host
    restart: unless-stopped

  postgres-db:
    container_name: postgres-db
    image: postgres:15.1-bullseye
    env_file:
      - .env.dev
    network_mode: host
    restart: unless-stopped