version: '3.5'
services:

  app:
    container_name: app
    image: node:21.7
    volumes:
      - ./backend/:/usr/src/app
    tty: true
    stdin_open: true
    env_file:
      - .env.dev
    network_mode: host


  postgres-db:
    container_name: postgres-db
    image: postgres:15.1-bullseye
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    restart: unless-stopped
    network_mode: host

  frontend:
    container_name: frontend
    image: node:alpine
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    restart: always
    network_mode: host